---
swagger: "2.0"
info:
  description: "Criação de uma API com nodeJS, para disponibilizar dados do livro\
    \ de Monstros do D&D 5e, esse projeto é um trabalho em grupo da materia Arquitetura\
    \ de computadores, que visa colaborar com a comunidade de RPG de mesa. "
  version: "1.0.0"
  title: "API Monster D&D"
host: "0.0.0.0:8080"
tags:
- name: "Monstro"
  description: ""
  externalDocs:
    description: "Find out more"
    url: "https://github.com/laurencioScript/api_monster"
paths:
  /monster/register:
    post:
      tags:
      - "Monstro"
      summary: ""
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Cadastra os monstros no banco de dados."
        required: true
        schema:
          $ref: "#/definitions/Register"
      responses:
        200:
          description: "Exibe todos os monstros cadastrados"
        400:
          description: " ta bugado me chama laurencio.arkauss@gmail.com "
      x-swagger-router-controller: "Monstro"
  /monster/getMonsterId=id:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Retorna todos os dados de um monstro especifico."
      operationId: "getMonsterId"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Identificação do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "sucesso na operação"
          schema:
            $ref: "#/definitions/Monstro"
        404:
          description: "ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getMonsterName=name:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Retorna todos os dados de um monstro especifico."
      operationId: "getMonsterName"
      produces:
      - "application/json"
      parameters:
      - name: "nome"
        in: "path"
        description: "nome do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "sucesso na operação"
          schema:
            $ref: "#/definitions/Monstro"
        400:
          description: " ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getMonster=tipo,tamanho,desafio,tendencia,ca,pv:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null"
      operationId: "getMonster"
      produces:
      - "application/json"
      parameters:
      - name: "tipo"
        in: "path"
        description: "tipo do monstro"
        required: true
        type: "string"
      - name: "tamanho"
        in: "path"
        description: "tamanho do monstro"
        required: true
        type: "string"
      - name: "desafio"
        in: "path"
        description: "desafio do monstro"
        required: true
        type: "string"
      - name: "tendencia"
        in: "path"
        description: "tendencia do monstro(sigla em maiusculo)"
        required: true
        type: "string"
      - name: "ca"
        in: "path"
        description: "classe de armadura do monstro"
        required: true
        type: "integer"
      - name: "pv"
        in: "path"
        description: "pontos de vida do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_Monstros"
        400:
          description: " ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getAtrib=for,des,con,int,sab,car:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getAtrib"
      produces:
      - "application/json"
      parameters:
      - name: "forca"
        in: "path"
        description: "valor de força do monstro"
        required: true
        type: "integer"
      - name: "destreza"
        in: "path"
        description: "valor de destreza do monstro"
        required: true
        type: "integer"
      - name: "constituicao"
        in: "path"
        description: "valor de constituição do monstro"
        required: true
        type: "integer"
      - name: "inteligencia"
        in: "path"
        description: "valor de inteligencia do monstro"
        required: true
        type: "integer"
      - name: "sabedoria"
        in: "path"
        description: "valor de sabedoria do monstro"
        required: true
        type: "integer"
      - name: "carisma"
        in: "path"
        description: "valor de carisma do monstro"
        required: true
        type: "integer"
      responses:
        200:
          description: "sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_1_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getDesloc=escalada,voo,escavacao,natacao,deslocamento:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getDesloc"
      produces:
      - "application/json"
      parameters:
      - name: "escalada"
        in: "path"
        description: "valor de escalada do monstro"
        required: true
        type: "number"
      - name: "voo"
        in: "path"
        description: "valor de voo do monstro"
        required: true
        type: "number"
      - name: "escavacao"
        in: "path"
        description: "valor de escavação do monstro"
        required: true
        type: "number"
      - name: "natacao"
        in: "path"
        description: "valor de natação do monstro"
        required: true
        type: "number"
      - name: "deslocamento"
        in: "path"
        description: "valor de deslocamento do monstro"
        required: true
        type: "number"
      responses:
        200:
          description: "sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_2_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getPericia=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getPericia"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "pericia do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "pericia do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "pericia do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_3_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getIdioma=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getIdioma"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "idioma do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "idioma do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "idioma do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_4_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getSentido=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getSentido"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "sentido do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "sentido do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "sentido do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_5_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getResistenciaDano=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getResistenciaDano"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "resistencia dano do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "resistencia dano do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "resistencia dano do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_6_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getVulnerabilidade=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getVulnerabilidade"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "vulnerabilidade do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "vulnerabilidade do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "vulnerabilidade do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_7_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getTesteResistencia=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getTesteResitencia"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "teste de resistencia do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "teste de resistencia do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "teste de resistencia do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_8_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getImunidade=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getImunidade"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "imunidade do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "imunidade do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "imunidade do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_9_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
  /monster/getEquipamentos=parm1,parm2,parm3:
    get:
      tags:
      - "Monstro"
      summary: ""
      description: "Busca todos os monstros de acordo com o parametros passados, nã\
        o deixe espaço vazio substitua por null."
      operationId: "getEquipamentos"
      produces:
      - "application/json"
      parameters:
      - name: "parm1"
        in: "path"
        description: "equipamento do monstro"
        required: true
        type: "string"
      - name: "parm2"
        in: "path"
        description: "equipamento do monstro"
        required: true
        type: "string"
      - name: "parm3"
        in: "path"
        description: "equipamento do monstro"
        required: true
        type: "string"
      responses:
        200:
          description: "Sucesso na operação"
          schema:
            type: "object"
            properties:
              count:
                type: "integer"
              Monstros:
                type: "array"
                items:
                  $ref: "#/definitions/inline_response_200_10_Monstros"
        400:
          description: "Ta bugado me chama laurencio.arkauss@gmail.com "
        404:
          description: "Ausência de parâmetros"
      x-swagger-router-controller: "Monstro"
definitions:
  Register:
    type: "array"
    items:
      $ref: "#/definitions/Register_inner"
  Monstro:
    type: "object"
    properties:
      count:
        type: "integer"
      monstros:
        type: "array"
        items:
          $ref: "#/definitions/Monstro_monstros"
    example:
      count: 0
      monstros:
      - tipo: "tipo"
        tracos:
        - tipo: "tipo"
          descricao: 6
        - tipo: "tipo"
          descricao: 6
        teste_resistencia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        pericia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        tendencia: "tendencia"
        deloscamento:
          escalada: 3.61607674925191080461672754609026014804840087890625
          deslocamento: 7.3862819483858839220147274318151175975799560546875
          natacao: 1.231513536777255612975068288506008684635162353515625
          voo: 2.027123023002321833274663731572218239307403564453125
          escavacao: 4.1456080298839363962315474054776132106781005859375
        vulnerabilidade:
        - "vulnerabilidade"
        - "vulnerabilidade"
        nome: "nome"
        idioma:
        - "idioma"
        - "idioma"
        tamanho: "tamanho"
        acao_lendaria:
        - tipo: "tipo"
          descricao: "descricao"
        - tipo: "tipo"
          descricao: "descricao"
        resistencia_dano:
        - "resistencia_dano"
        - "resistencia_dano"
        sentido:
        - tipo: "tipo"
          alcance: 1
        - tipo: "tipo"
          alcance: 1
        desafio: "desafio"
        equipamento:
        - "equipamento"
        - "equipamento"
        xp: 6
        id: "id"
        atributo:
          carisma: 9
          inteligencia: 2
          forca: 1
          destreza: 5
          constituicao: 5
          sabedoria: 7
        imunidade:
        - "imunidade"
        - "imunidade"
        acao:
        - tipo: "tipo"
          descricao: "descricao"
        - tipo: "tipo"
          descricao: "descricao"
      - tipo: "tipo"
        tracos:
        - tipo: "tipo"
          descricao: 6
        - tipo: "tipo"
          descricao: 6
        teste_resistencia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        pericia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        tendencia: "tendencia"
        deloscamento:
          escalada: 3.61607674925191080461672754609026014804840087890625
          deslocamento: 7.3862819483858839220147274318151175975799560546875
          natacao: 1.231513536777255612975068288506008684635162353515625
          voo: 2.027123023002321833274663731572218239307403564453125
          escavacao: 4.1456080298839363962315474054776132106781005859375
        vulnerabilidade:
        - "vulnerabilidade"
        - "vulnerabilidade"
        nome: "nome"
        idioma:
        - "idioma"
        - "idioma"
        tamanho: "tamanho"
        acao_lendaria:
        - tipo: "tipo"
          descricao: "descricao"
        - tipo: "tipo"
          descricao: "descricao"
        resistencia_dano:
        - "resistencia_dano"
        - "resistencia_dano"
        sentido:
        - tipo: "tipo"
          alcance: 1
        - tipo: "tipo"
          alcance: 1
        desafio: "desafio"
        equipamento:
        - "equipamento"
        - "equipamento"
        xp: 6
        id: "id"
        atributo:
          carisma: 9
          inteligencia: 2
          forca: 1
          destreza: 5
          constituicao: 5
          sabedoria: 7
        imunidade:
        - "imunidade"
        - "imunidade"
        acao:
        - tipo: "tipo"
          descricao: "descricao"
        - tipo: "tipo"
          descricao: "descricao"
  inline_response_200_Monstros:
    properties:
      _id:
        type: "string"
      nome:
        type: "string"
      desafio:
        type: "string"
      pv:
        type: "string"
      ca:
        type: "integer"
      tipo:
        type: "string"
      tamanho:
        type: "string"
    example:
      tipo: "tipo"
      tamanho: "tamanho"
      pv: "pv"
      desafio: "desafio"
      nome: "nome"
      _id: "_id"
      ca: 6
  inline_response_200:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_Monstros"
    example:
      Monstros:
      - tipo: "tipo"
        tamanho: "tamanho"
        pv: "pv"
        desafio: "desafio"
        nome: "nome"
        _id: "_id"
        ca: 6
      - tipo: "tipo"
        tamanho: "tamanho"
        pv: "pv"
        desafio: "desafio"
        nome: "nome"
        _id: "_id"
        ca: 6
      count: 0
  inline_response_200_1_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      Força:
        type: "integer"
      Destreza:
        type: "integer"
      Constituição:
        type: "integer"
      Inteligencia:
        type: "integer"
      Sabedoria:
        type: "integer"
      Carisma:
        type: "integer"
    example:
      Constituição: 5
      Destreza: 1
      Inteligencia: 5
      nome: "nome"
      id: "id"
      Força: 6
      Sabedoria: 2
      Carisma: 7
  inline_response_200_1:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_1_Monstros"
    example:
      Monstros:
      - Constituição: 5
        Destreza: 1
        Inteligencia: 5
        nome: "nome"
        id: "id"
        Força: 6
        Sabedoria: 2
        Carisma: 7
      - Constituição: 5
        Destreza: 1
        Inteligencia: 5
        nome: "nome"
        id: "id"
        Força: 6
        Sabedoria: 2
        Carisma: 7
      count: 0
  inline_response_200_2_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      Escalada:
        type: "number"
      Voo:
        type: "number"
      Escavação:
        type: "number"
      Natação:
        type: "number"
      Deslocamento:
        type: "number"
    example:
      Deslocamento: 2.3021358869347654518833223846741020679473876953125
      Voo: 1.46581298050294517310021547018550336360931396484375
      Escalada: 6.02745618307040320615897144307382404804229736328125
      nome: "nome"
      Escavação: 5.962133916683182377482808078639209270477294921875
      id: "id"
      Natação: 5.63737665663332876420099637471139430999755859375
  inline_response_200_2:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_2_Monstros"
    example:
      Monstros:
      - Deslocamento: 2.3021358869347654518833223846741020679473876953125
        Voo: 1.46581298050294517310021547018550336360931396484375
        Escalada: 6.02745618307040320615897144307382404804229736328125
        nome: "nome"
        Escavação: 5.962133916683182377482808078639209270477294921875
        id: "id"
        Natação: 5.63737665663332876420099637471139430999755859375
      - Deslocamento: 2.3021358869347654518833223846741020679473876953125
        Voo: 1.46581298050294517310021547018550336360931396484375
        Escalada: 6.02745618307040320615897144307382404804229736328125
        nome: "nome"
        Escavação: 5.962133916683182377482808078639209270477294921875
        id: "id"
        Natação: 5.63737665663332876420099637471139430999755859375
      count: 0
  inline_response_200_3_pericia:
    properties:
      tipo:
        type: "string"
      bonus:
        type: "integer"
    example:
      tipo: "tipo"
      bonus: 1
  inline_response_200_3_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      pericia:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_pericia"
    example:
      pericia:
      - tipo: "tipo"
        bonus: 1
      - tipo: "tipo"
        bonus: 1
      nome: "nome"
      id: "id"
  inline_response_200_3:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_Monstros"
    example:
      Monstros:
      - pericia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        nome: "nome"
        id: "id"
      - pericia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        nome: "nome"
        id: "id"
      count: 0
  inline_response_200_4_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      idioma:
        type: "array"
        items:
          type: "string"
    example:
      nome: "nome"
      idioma:
      - "idioma"
      - "idioma"
      id: "id"
  inline_response_200_4:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_4_Monstros"
    example:
      Monstros:
      - nome: "nome"
        idioma:
        - "idioma"
        - "idioma"
        id: "id"
      - nome: "nome"
        idioma:
        - "idioma"
        - "idioma"
        id: "id"
      count: 0
  inline_response_200_5_sentido:
    properties:
      tipo:
        type: "string"
      alcance:
        type: "integer"
    example:
      tipo: "tipo"
      alcance: 1
  inline_response_200_5_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      sentido:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_5_sentido"
    example:
      sentido:
      - tipo: "tipo"
        alcance: 1
      - tipo: "tipo"
        alcance: 1
      nome: "nome"
      id: "id"
  inline_response_200_5:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_5_Monstros"
    example:
      Monstros:
      - sentido:
        - tipo: "tipo"
          alcance: 1
        - tipo: "tipo"
          alcance: 1
        nome: "nome"
        id: "id"
      - sentido:
        - tipo: "tipo"
          alcance: 1
        - tipo: "tipo"
          alcance: 1
        nome: "nome"
        id: "id"
      count: 0
  inline_response_200_6_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      resistencia_dano:
        type: "array"
        items:
          type: "string"
    example:
      resistencia_dano:
      - "resistencia_dano"
      - "resistencia_dano"
      nome: "nome"
      id: "id"
  inline_response_200_6:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_6_Monstros"
    example:
      Monstros:
      - resistencia_dano:
        - "resistencia_dano"
        - "resistencia_dano"
        nome: "nome"
        id: "id"
      - resistencia_dano:
        - "resistencia_dano"
        - "resistencia_dano"
        nome: "nome"
        id: "id"
      count: 0
  inline_response_200_7_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      vulnerabilidade:
        type: "array"
        items:
          type: "string"
    example:
      vulnerabilidade:
      - "vulnerabilidade"
      - "vulnerabilidade"
      nome: "nome"
      id: "id"
  inline_response_200_7:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_7_Monstros"
    example:
      Monstros:
      - vulnerabilidade:
        - "vulnerabilidade"
        - "vulnerabilidade"
        nome: "nome"
        id: "id"
      - vulnerabilidade:
        - "vulnerabilidade"
        - "vulnerabilidade"
        nome: "nome"
        id: "id"
      count: 0
  inline_response_200_8_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      teste_resistencia:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_pericia"
    example:
      teste_resistencia:
      - tipo: "tipo"
        bonus: 1
      - tipo: "tipo"
        bonus: 1
      nome: "nome"
      id: "id"
  inline_response_200_8:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_8_Monstros"
    example:
      Monstros:
      - teste_resistencia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        nome: "nome"
        id: "id"
      - teste_resistencia:
        - tipo: "tipo"
          bonus: 1
        - tipo: "tipo"
          bonus: 1
        nome: "nome"
        id: "id"
      count: 0
  inline_response_200_9_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      imunidade:
        type: "array"
        items:
          type: "string"
    example:
      nome: "nome"
      id: "id"
      imunidade:
      - "imunidade"
      - "imunidade"
  inline_response_200_9:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_9_Monstros"
    example:
      Monstros:
      - nome: "nome"
        id: "id"
        imunidade:
        - "imunidade"
        - "imunidade"
      - nome: "nome"
        id: "id"
        imunidade:
        - "imunidade"
        - "imunidade"
      count: 0
  inline_response_200_10_Monstros:
    properties:
      id:
        type: "string"
      nome:
        type: "string"
      equipamento:
        type: "array"
        items:
          type: "string"
    example:
      equipamento:
      - "equipamento"
      - "equipamento"
      nome: "nome"
      id: "id"
  inline_response_200_10:
    properties:
      count:
        type: "integer"
      Monstros:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_10_Monstros"
    example:
      Monstros:
      - equipamento:
        - "equipamento"
        - "equipamento"
        nome: "nome"
        id: "id"
      - equipamento:
        - "equipamento"
        - "equipamento"
        nome: "nome"
        id: "id"
      count: 0
  Register_inner:
    properties:
      desafio:
        type: "integer"
      xp:
        type: "integer"
      nome:
        type: "string"
      tipo:
        type: "string"
      tamanho:
        type: "string"
      tendencia:
        type: "string"
      pv:
        type: "string"
      ca:
        type: "integer"
  Monstro_atributo:
    properties:
      forca:
        type: "integer"
      destreza:
        type: "integer"
      constituicao:
        type: "integer"
      inteligencia:
        type: "integer"
      sabedoria:
        type: "integer"
      carisma:
        type: "integer"
    example:
      carisma: 9
      inteligencia: 2
      forca: 1
      destreza: 5
      constituicao: 5
      sabedoria: 7
  Monstro_deloscamento:
    properties:
      escalada:
        type: "number"
      voo:
        type: "number"
      escavacao:
        type: "number"
      deslocamento:
        type: "number"
      natacao:
        type: "number"
    example:
      escalada: 3.61607674925191080461672754609026014804840087890625
      deslocamento: 7.3862819483858839220147274318151175975799560546875
      natacao: 1.231513536777255612975068288506008684635162353515625
      voo: 2.027123023002321833274663731572218239307403564453125
      escavacao: 4.1456080298839363962315474054776132106781005859375
  Monstro_tracos:
    properties:
      tipo:
        type: "string"
      descricao:
        type: "integer"
    example:
      tipo: "tipo"
      descricao: 6
  Monstro_acao:
    properties:
      tipo:
        type: "string"
      descricao:
        type: "string"
    example:
      tipo: "tipo"
      descricao: "descricao"
  Monstro_monstros:
    properties:
      id:
        type: "string"
      desafio:
        type: "string"
      xp:
        type: "integer"
      nome:
        type: "string"
      tipo:
        type: "string"
      tamanho:
        type: "string"
      tendencia:
        type: "string"
      atributo:
        $ref: "#/definitions/Monstro_atributo"
      deloscamento:
        $ref: "#/definitions/Monstro_deloscamento"
      idioma:
        type: "array"
        items:
          type: "string"
      imunidade:
        type: "array"
        items:
          type: "string"
      vulnerabilidade:
        type: "array"
        items:
          type: "string"
      sentido:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_5_sentido"
      teste_resistencia:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_pericia"
      pericia:
        type: "array"
        items:
          $ref: "#/definitions/inline_response_200_3_pericia"
      resistencia_dano:
        type: "array"
        items:
          type: "string"
      tracos:
        type: "array"
        items:
          $ref: "#/definitions/Monstro_tracos"
      acao:
        type: "array"
        items:
          $ref: "#/definitions/Monstro_acao"
      acao_lendaria:
        type: "array"
        items:
          $ref: "#/definitions/Monstro_acao"
      equipamento:
        type: "array"
        items:
          type: "string"
    example:
      tipo: "tipo"
      tracos:
      - tipo: "tipo"
        descricao: 6
      - tipo: "tipo"
        descricao: 6
      teste_resistencia:
      - tipo: "tipo"
        bonus: 1
      - tipo: "tipo"
        bonus: 1
      pericia:
      - tipo: "tipo"
        bonus: 1
      - tipo: "tipo"
        bonus: 1
      tendencia: "tendencia"
      deloscamento:
        escalada: 3.61607674925191080461672754609026014804840087890625
        deslocamento: 7.3862819483858839220147274318151175975799560546875
        natacao: 1.231513536777255612975068288506008684635162353515625
        voo: 2.027123023002321833274663731572218239307403564453125
        escavacao: 4.1456080298839363962315474054776132106781005859375
      vulnerabilidade:
      - "vulnerabilidade"
      - "vulnerabilidade"
      nome: "nome"
      idioma:
      - "idioma"
      - "idioma"
      tamanho: "tamanho"
      acao_lendaria:
      - tipo: "tipo"
        descricao: "descricao"
      - tipo: "tipo"
        descricao: "descricao"
      resistencia_dano:
      - "resistencia_dano"
      - "resistencia_dano"
      sentido:
      - tipo: "tipo"
        alcance: 1
      - tipo: "tipo"
        alcance: 1
      desafio: "desafio"
      equipamento:
      - "equipamento"
      - "equipamento"
      xp: 6
      id: "id"
      atributo:
        carisma: 9
        inteligencia: 2
        forca: 1
        destreza: 5
        constituicao: 5
        sabedoria: 7
      imunidade:
      - "imunidade"
      - "imunidade"
      acao:
      - tipo: "tipo"
        descricao: "descricao"
      - tipo: "tipo"
        descricao: "descricao"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
